// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// actflow_predict_batch_cpp
arma::cube actflow_predict_batch_cpp(const arma::cube& act, const arma::cube& fc, bool remove_diag);
RcppExport SEXP _actflower_actflow_predict_batch_cpp(SEXP actSEXP, SEXP fcSEXP, SEXP remove_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type act(actSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type fc(fcSEXP);
    Rcpp::traits::input_parameter< bool >::type remove_diag(remove_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(actflow_predict_batch_cpp(act, fc, remove_diag));
    return rcpp_result_gen;
END_RCPP
}
// actflow_fullcomp_batch_cpp
Rcpp::List actflow_fullcomp_batch_cpp(const arma::cube& act, const arma::cube& fc, const arma::cube& target, bool remove_diag);
RcppExport SEXP _actflower_actflow_fullcomp_batch_cpp(SEXP actSEXP, SEXP fcSEXP, SEXP targetSEXP, SEXP remove_diagSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type act(actSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type fc(fcSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< bool >::type remove_diag(remove_diagSEXP);
    rcpp_result_gen = Rcpp::wrap(actflow_fullcomp_batch_cpp(act, fc, target, remove_diag));
    return rcpp_result_gen;
END_RCPP
}
// compare_fullcomp_cpp
Rcpp::List compare_fullcomp_cpp(const arma::cube& target, const arma::cube& pred);
RcppExport SEXP _actflower_compare_fullcomp_cpp(SEXP targetSEXP, SEXP predSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const arma::cube& >::type pred(predSEXP);
    rcpp_result_gen = Rcpp::wrap(compare_fullcomp_cpp(target, pred));
    return rcpp_result_gen;
END_RCPP
}
// corr_fc_cpp
arma::mat corr_fc_cpp(const arma::mat& x_nodes_by_time);
RcppExport SEXP _actflower_corr_fc_cpp(SEXP x_nodes_by_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x_nodes_by_time(x_nodes_by_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(corr_fc_cpp(x_nodes_by_time));
    return rcpp_result_gen;
END_RCPP
}
// corr_fc_batch_cpp
arma::cube corr_fc_batch_cpp(const arma::cube& x_nodes_by_time);
RcppExport SEXP _actflower_corr_fc_batch_cpp(SEXP x_nodes_by_timeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::cube& >::type x_nodes_by_time(x_nodes_by_timeSEXP);
    rcpp_result_gen = Rcpp::wrap(corr_fc_batch_cpp(x_nodes_by_time));
    return rcpp_result_gen;
END_RCPP
}
// multreg_fc_cpp
arma::mat multreg_fc_cpp(const arma::mat& x_nodes_by_time, double ridge);
RcppExport SEXP _actflower_multreg_fc_cpp(SEXP x_nodes_by_timeSEXP, SEXP ridgeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type x_nodes_by_time(x_nodes_by_timeSEXP);
    Rcpp::traits::input_parameter< double >::type ridge(ridgeSEXP);
    rcpp_result_gen = Rcpp::wrap(multreg_fc_cpp(x_nodes_by_time, ridge));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_actflower_actflow_predict_batch_cpp", (DL_FUNC) &_actflower_actflow_predict_batch_cpp, 3},
    {"_actflower_actflow_fullcomp_batch_cpp", (DL_FUNC) &_actflower_actflow_fullcomp_batch_cpp, 4},
    {"_actflower_compare_fullcomp_cpp", (DL_FUNC) &_actflower_compare_fullcomp_cpp, 2},
    {"_actflower_corr_fc_cpp", (DL_FUNC) &_actflower_corr_fc_cpp, 1},
    {"_actflower_corr_fc_batch_cpp", (DL_FUNC) &_actflower_corr_fc_batch_cpp, 1},
    {"_actflower_multreg_fc_cpp", (DL_FUNC) &_actflower_multreg_fc_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_actflower(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
