# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

actflow_predict_batch_cpp <- function(act, fc, remove_diag = TRUE) {
    .Call(`_actflower_actflow_predict_batch_cpp`, act, fc, remove_diag)
}

compare_fullcomp_cpp <- function(target, pred) {
    .Call(`_actflower_compare_fullcomp_cpp`, target, pred)
}

corr_fc_cpp <- function(x_nodes_by_time) {
    .Call(`_actflower_corr_fc_cpp`, x_nodes_by_time)
}

multreg_fc_cpp <- function(x_nodes_by_time, ridge = 0.0) {
    .Call(`_actflower_multreg_fc_cpp`, x_nodes_by_time, ridge)
}

